### ISSUE TITLE
Not compatible with android (or IOS)

### ISSUE THREAD

**Issue by OneTenOneTwenty** [WilloIzCitron/ArchiveDustry-Java#6] opened 2024-06-16 08:37 UTC
The moment this mod is loaded to Mindustry, it immediately crashes.

**Comment by WilloIzCitron** [comment] 2024-06-16 11:35
Uhh can you send the log?

**Comment by WilloIzCitron** [comment] 2024-06-16 11:40
1. iOS won't allow Java mod
2. Maybe if the game crashed caused by low memory (I have 8gb of ram on my phone, it work)
3. The l2d was being splitted from mod sprites, frame will be loaded from external l2d directory at mindustry appdata(windows)(for android io.anuke.mindustry) (it will be released on v1.3)

**Comment by OneTenOneTwenty** [comment] 2024-06-16 11:49
Unfortunately, I could not collect a crash log. The moment Mindustry restarts to load the mod (alone), it crashes. But, I'll be patient until that update comes.

By the way, I use a Vivo Y11 (2019 model) with 3gb ram, it might have used too much RAM and forced the system to close the app.

**Comment by WilloIzCitron** [comment] 2024-06-16 11:58
Kinda true, if v1.3 release, the update will optimize this mod

**Comment by OneTenOneTwenty** [comment] 2024-06-16 12:09
Thanks

**Closed** 2024-06-24 12:09 UTC
